### PR TITLE
Separate each group with a space in ,list

### PR DESCRIPTION
**Pull request by taahamahdi**
Improves readability substantially

### CODE REVIEW

**Comment by Brainicism** [comment]
There's a lack of space intentionally to maximize the number of groups that can fit in the message, so it can be re-used with `,groups`

**Comment by taahamahdi** [comment]
It is the only way for the user to see all the groups they have set if they go beyond what ,groups shows. Should we sacrifice readability for fitting in more groups when we already have the ability to send the groups list as a file if it's too long?

**Comment by Brainicism** [comment]
There are cases where the text will fit in a `,groups` message when theres no space in the delimiter, but won't fit if there is a space. Unless we have two separate options to have space vs non-space, we can't satisfy both use cases at the same time

**Comment by taahamahdi** [comment]
Understood, I'll close this PR

**Pull request closed without merging**
